export { HeroHome as HeroSection } from './hero-home'
export { MetricsSection } from './metrics'
export { SolutionsSection } from './solutions'
export { WhyTeloosSection } from './why-teloos'
export { AnalyticsSection } from './analytics-section'
export { IntegrationsSection } from './integrations'
export { CtaSection } from './cta-section'
export { PlansSection } from './plans-section'
